name: Serverless Deployement Example

# Triggers the action everty time there is a code push to the master branch
on:
  push:
    branches:
      - master

# Specify what jobs to run
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest 
    env: #Setup environmental variables for serverless deployment
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{secrets.AWS_DEFAULT_REGION}}

    steps:
      - uses: actions/checkout@v2 
      
      - name: Install Serverless
        run: npm install -g serverless
      
      - name: Install dependencies
        run: npm install  
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Run command
        run: serverless deploy --stage slspoc