name: Serverless Deployement Example

# Triggers the action everty time there is a code push to the master branch
on:
  push:
    branches:
      - master

# Specify what jobs to run
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest 
    env: #Setup environmental variables for serverless deployment
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
        

    steps:
      - uses: actions/checkout@v2 
      
      - name: Install Serverless
        run: npm install -g serverless
      
      - name: Install dependencies
        run: npm install  
      
          
      - name: Run command
        run: serverless deploy --stage slspoc