name: Serverless Deployement Example

# Triggers the action everty time there is a code push to the master branch
on:
  push:
    branches:
      - master

# Specify what jobs to run
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest 
    env: #Setup environmental variables for serverless deployment
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}

    steps:
      - uses: actions/checkout@v2 

      - name: npm install dependencies
        run: npm install  
      - name: Serverless
        uses: teakowadeprecated/Serverless-Action@v2.4.0
        with:
          args: deploy --stage slspoc
